import { HttpStatus } from '@nestjs/common';

export enum ErrorCode {
  FORBIDDEN = 'FORBIDDEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_DELETED = 'USER_DELETED',
  INVALID_ROLE = 'INVALID_ROLE',
  INVALID_PROVIDER = 'INVALID_PROVIDER',
  INVALID_TOKEN = 'INVALID_TOKEN',
  QUEST_NOT_FOUND = 'QUEST_NOT_FOUND',
  USER_QUEST_NOT_FOUND = 'USER_QUEST_NOT_FOUND',
  REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
  USER_REWARD_NOT_FOUND = 'USER_REWARD_NOT_FOUND',
  VERIFICATION_NOT_FOUND = 'VERIFICATION_NOT_FOUND',
}

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  [ErrorCode.FORBIDDEN]: HttpStatus.FORBIDDEN,
  [ErrorCode.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.USER_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [ErrorCode.USER_DELETED]: HttpStatus.NOT_FOUND,
  [ErrorCode.INVALID_ROLE]: HttpStatus.BAD_REQUEST,
  [ErrorCode.INVALID_PROVIDER]: HttpStatus.BAD_REQUEST,
  [ErrorCode.INVALID_TOKEN]: HttpStatus.BAD_REQUEST,
  [ErrorCode.QUEST_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.USER_QUEST_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.REWARD_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.USER_REWARD_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [ErrorCode.VERIFICATION_NOT_FOUND]: HttpStatus.NOT_FOUND,
};
